"""ABC theme — soft light palette (off-white, slate text, teal accent).
Brand red/yellow lives only inside the logo PNG; the UI stays soft and high-contrast.
"""
import base64
import random
from pathlib import Path

import streamlit as st

LOGO_PATH = Path(__file__).parent / "assets" / "logo.png"
LOGO_FALLBACK = Path(__file__).parent / "assets" / "logo.png"

# ─── Soft light palette ────────────────────────────────────
# Soft off-white background, slate text, teal/blue accent.
BG_DEEP = "#F8FAFC"          # page background — soft off-white
BG_PANEL = "#FFFFFF"          # cards (pure white for crisp contrast)
BG_PANEL_HI = "#F1F5F9"       # raised / hover panel
BORDER = "#E2E8F0"            # subtle dividers
BORDER_HI = "#CBD5E1"         # stronger dividers

TEXT_HI = "#0F172A"           # primary text (slate-900)
TEXT_MID = "#334155"          # secondary text (slate-700)
TEXT_MUTED = "#64748B"        # captions / hints (slate-500)

ACCENT = "#0EA5E9"            # sky-500 — primary actions
ACCENT_HI = "#0284C7"         # sky-600 — hover
ACCENT_DEEP = "#0369A1"       # sky-700 — pressed
ACCENT_SOFT_BG = "#E0F2FE"    # sky-100 — soft tag backgrounds

SUCCESS = "#16A34A"           # green-600
WARN = "#D97706"              # amber-600
DANGER = "#DC2626"            # red-600
ACCENT_VIOLET = "#7C3AED"     # violet-600 — secondary accent

WHITE = "#FFFFFF"

# Motivational quotes (rotate randomly) — bilingual
QUOTES = {
    "en": [
        "Stronger than yesterday.",
        "The body achieves what the mind believes.",
        "Discipline is the bridge between goals and accomplishment.",
        "Sweat now, shine later.",
        "Train insane or remain the same.",
        "Your only limit is you.",
        "Push harder than yesterday if you want a different tomorrow.",
        "Success starts with self-discipline.",
        "Fall in love with the process.",
        "Excuses don't burn calories.",
        "The pain you feel today is the strength you feel tomorrow.",
        "Hustle for that muscle.",
        "Numbers don't lie. Track everything.",
        "Be stronger than your strongest excuse.",
        "Champions are made in the fitness centre, defined by the data.",
    ],
    "hi": [
        "आज से कल बेहतर बनो।",
        "जो मन सोचता है, शरीर कर दिखाता है।",
        "अनुशासन ही सपनों को सच्चाई बनाता है।",
        "आज पसीना, कल कामयाबी।",
        "बदलो या वही रह जाओ।",
        "तुम्हारी सीमा सिर्फ तुम हो।",
        "कल बदलना है तो आज और मेहनत करो।",
        "सफलता का पहला कदम है आत्म-अनुशासन।",
        "प्रक्रिया से प्यार करो, परिणाम मिलेगा।",
        "बहाने कैलोरी नहीं जलाते।",
        "आज का दर्द कल की ताकत है।",
        "मेहनत से मसल्स बनती हैं।",
        "नंबर्स झूठ नहीं बोलते। सब मापो।",
        "अपने सबसे बड़े बहाने से ताकतवर बनो।",
        "चैंपियन जिम में बनते हैं — डेटा से पहचाने जाते हैं।",
    ],
}

# ─── Bilingual UI strings ──────────────────────────────────
T = {
    "en": {
        "powered_by": "POWERED BY AI",
        "since": "Since 2020",
        "language": "LANGUAGE",
        "subtitle_home": "Analytics Dashboard · Since 2020",
        "stats_that_matter": "KEY METRICS",
        "fy_revenue": "FY Revenue",
        "fy_profit": "FY Profit",
        "total_revenue": "Total Revenue",
        "operating_cost": "Operating Cost",
        "net_profit": "Net Profit",
        "gross_margin": "Gross Margin",
        "best_margin": "Best Margin",
        "months_active": "Months Active",
        "loss_month_s": "loss month",
        "loss_months_s": "loss months",
        "latest_month": "LATEST MONTH",
        "revenue": "Revenue",
        "expenses": "Expenses",
        "profit": "Profit",
        "loss": "LOSS",
        "margin": "margin",
        "ultra_premium": "Ultra / Premium",
        "year_highlights": "YEAR HIGHLIGHTS",
        "best_profit_month": "🏆 BEST PROFIT MONTH",
        "worst_profit_month": "⚠️ WORST PROFIT MONTH",
        "anomalies_detected": "⚠️ ANOMALIES DETECTED",
        "explore_data": "EXPLORE THE DATA",
        "nav_monthly_briefs": "MONTHLY BRIEFS",
        "nav_monthly_sub": "Plain-English summary per month",
        "nav_annual": "ANNUAL REVIEWS",
        "nav_annual_sub": "Owner + Accountant versions",
        "nav_anomalies": "ANOMALY REPORTS",
        "nav_anomalies_sub": "AI-flagged data issues + actions",
        "nav_qa": "Q&A CHAT",
        "nav_qa_sub": "Ask anything · cited answers",
        "use_sidebar": "👈 Use the sidebar to navigate",
        "content_generated": "CONTENT GENERATED BY AI",
        "monthly_briefs_label": "Monthly Briefs",
        "anomaly_reports_label": "Anomaly Reports",
        "annual_reviews_label": "Annual Reviews",
        "brand_bar_footer": "POWERED BY CLAUDE HAIKU 4.5 · ALL DATA LOCAL · ₹5/MONTH OPERATING COST",
        "err_data_load": "⚠️ Could not load P&L data",
        "info_master_file": "Make sure `ABC Master sample.xlsx` exists in the output folder.",
        "page_briefs_title": "MONTHLY BRIEFS",
        "page_briefs_sub": "One-page summary per month · auto-generated · forwardable",
        "briefs_folder_missing": "📁 Briefs folder not found yet.",
        "run_narrate_month": "Run `python narrate_month.py` to generate the first brief.",
        "no_briefs_found": "No monthly briefs found.",
        "n_briefs_available": "📚 **{n} BRIEFS AVAILABLE**",
        "select_month": "🗓 SELECT MONTH:",
        "download_md": "⬇ MARKDOWN",
        "download_pdf": "⬇ PDF",
        "source_label": "📄 Source:",
        "brand_bar_monthly": "PUSH HARDER · MEASURE EVERYTHING · WIN MORE",
        "page_annual_title": "ANNUAL REVIEWS",
        "page_annual_sub": "Full year story · Owner version + Accountant version",
        "annual_folder_missing": "📁 Annual reviews folder not found yet.",
        "run_narrate_year": "Run `python narrate_year.py` to generate the first review.",
        "no_annual_found": "No annual reviews yet.",
        "fiscal_year": "📆 FISCAL YEAR:",
        "audience": "👥 AUDIENCE:",
        "owner": "Owner",
        "accountant": "Accountant",
        "side_by_side": "Side-by-side",
        "owner_version_short": "OWNER",
        "accountant_version_short": "ACCOUNTANT",
        "owner_version": "👤 OWNER VERSION",
        "accountant_version": "📊 ACCOUNTANT VERSION",
        "version_missing": "⚠️ Version not generated for this FY.",
        "download_short": "⬇ MD",
        "brand_bar_annual": "YEAR-END WINS START WITH MONTHLY DISCIPLINE",
        "page_anomaly_title": "ANOMALY REPORTS",
        "page_anomaly_sub": "AI catches what humans miss · with action recommendations",
        "anomaly_folder_missing": "📁 Anomalies folder not found yet.",
        "run_sentinel": "Run `python sentinel.py --all` to generate reports.",
        "no_anomaly_found": "No anomaly reports yet.",
        "severity_summary": "SEVERITY SUMMARY",
        "critical": "🚨 Critical",
        "needs_review": "⚠️ Needs Review",
        "minor": "🟡 Minor",
        "mostly_clean": "⚪ Mostly Clean",
        "clean": "✅ Clean",
        "all_reports": "ALL REPORTS",
        "filter_severity": "🔍 FILTER BY SEVERITY:",
        "no_match_filter": "ℹ️ No reports match the selected filters.",
        "brand_bar_anomaly": "CATCH IT EARLY · FIX IT FAST · STAY AHEAD",
        "page_qa_title": "ASK YOUR P&L",
        "page_qa_sub": "AI-powered Q&A · grounded in real ABC data · cited answers",
        "chat_controls": "💬 CHAT CONTROLS",
        "back_to_start": "🔄 BACK TO START",
        "clear_chat": "🗑 CLEAR CHAT",
        "save_session": "💾 SAVE MARKDOWN",
        "export_pdf": "📄 EXPORT PDF",
        "session_saved": "✅ Saved →",
        "nothing_to_save": "Nothing to save yet.",
        "tokens_used": "TOKENS USED",
        "input_tokens": "📥 Input",
        "output_tokens": "📤 Output",
        "cache_hits": "⚡ Cache hits",
        "kb_loaded": "📊 KNOWLEDGE BASE LOADED:",
        "months_briefs_meta": "{months} months · {briefs} brief(s)/report(s) · ~{tokens} tokens cached",
        "pick_question": "## 💡 PICK A QUESTION",
        "dig_deeper": "## 💡 DIG DEEPER",
        "chat_placeholder": "💪 Or type your own question...",
        "asking_claude": "💪 Lifting answers from data...",
        "err_no_key": "❌ Invalid or missing ANTHROPIC_API_KEY. Check `.env` file.",
        "err_rate_limit": "❌ Rate limited:",
        "err_api": "❌ API error",
        "err_parse": "❌ Failed to parse LLM response:",
        "brand_bar_qa": "KNOWLEDGE IS POWER · ASK ANYTHING · WIN EVERYTHING",
    },
    "hi": {
        "powered_by": "AI द्वारा संचालित",
        "since": "2020 से",
        "language": "भाषा",
        "subtitle_home": "एनालिटिक्स डैशबोर्ड · 2020 से",
        "stats_that_matter": "मुख्य मेट्रिक्स",
        "fy_revenue": "वार्षिक रेवेन्यू",
        "fy_profit": "वार्षिक लाभ",
        "total_revenue": "कुल रेवेन्यू",
        "operating_cost": "ऑपरेटिंग कॉस्ट",
        "net_profit": "शुद्ध लाभ",
        "gross_margin": "ग्रॉस मार्जिन",
        "best_margin": "सर्वोत्तम मार्जिन",
        "months_active": "सक्रिय महीने",
        "loss_month_s": "नुकसान का महीना",
        "loss_months_s": "नुकसान के महीने",
        "latest_month": "नवीनतम महीना",
        "revenue": "रेवेन्यू",
        "expenses": "खर्च",
        "profit": "लाभ",
        "loss": "नुकसान",
        "margin": "मार्जिन",
        "ultra_premium": "अल्ट्रा / प्रीमियम",
        "year_highlights": "साल की मुख्य बातें",
        "best_profit_month": "🏆 सबसे अच्छा लाभ का महीना",
        "worst_profit_month": "⚠️ सबसे ख़राब लाभ का महीना",
        "anomalies_detected": "⚠️ एनोमलीज़ पकड़ी गईं",
        "explore_data": "डेटा एक्सप्लोर करें",
        "nav_monthly_briefs": "मासिक ब्रीफ",
        "nav_monthly_sub": "हर महीने की सरल भाषा में रिपोर्ट",
        "nav_annual": "वार्षिक समीक्षा",
        "nav_annual_sub": "मालिक + अकाउंटेंट दोनों के लिए",
        "nav_anomalies": "एनोमली रिपोर्ट",
        "nav_anomalies_sub": "AI द्वारा फ्लैग्ड समस्याएँ + एक्शन",
        "nav_qa": "Q&A चैट",
        "nav_qa_sub": "कुछ भी पूछें · सोर्स के साथ जवाब",
        "use_sidebar": "👈 साइडबार से नेविगेट करें",
        "content_generated": "AI द्वारा बनाई गई कंटेंट",
        "monthly_briefs_label": "मासिक ब्रीफ",
        "anomaly_reports_label": "एनोमली रिपोर्ट",
        "annual_reviews_label": "वार्षिक समीक्षा",
        "brand_bar_footer": "Claude Haiku 4.5 द्वारा संचालित · डेटा लोकल · ₹5/महीना",
        "err_data_load": "⚠️ P&L डेटा लोड नहीं हो सका",
        "info_master_file": "सुनिश्चित करें कि `ABC Master sample.xlsx` आउटपुट फोल्डर में मौजूद है।",
        "page_briefs_title": "मासिक ब्रीफ",
        "page_briefs_sub": "हर महीने की एक-पेज समरी · ऑटो-जनरेटेड · आगे भेजने योग्य",
        "briefs_folder_missing": "📁 ब्रीफ फोल्डर अभी तक नहीं मिला।",
        "run_narrate_month": "पहला ब्रीफ बनाने के लिए चलाएँ: `python narrate_month.py`",
        "no_briefs_found": "कोई मासिक ब्रीफ नहीं मिला।",
        "n_briefs_available": "📚 **{n} ब्रीफ उपलब्ध**",
        "select_month": "🗓 महीना चुनें:",
        "download_md": "⬇ मार्कडाउन",
        "download_pdf": "⬇ PDF",
        "source_label": "📄 स्रोत:",
        "brand_bar_monthly": "और मेहनत · सब मापें · और जीतें",
        "page_annual_title": "वार्षिक समीक्षा",
        "page_annual_sub": "पूरे साल की कहानी · मालिक + अकाउंटेंट दोनों के लिए",
        "annual_folder_missing": "📁 वार्षिक रिपोर्ट फोल्डर अभी तक नहीं मिला।",
        "run_narrate_year": "पहली रिपोर्ट बनाने के लिए चलाएँ: `python narrate_year.py`",
        "no_annual_found": "कोई वार्षिक रिपोर्ट नहीं मिली।",
        "fiscal_year": "📆 वित्तीय वर्ष:",
        "audience": "👥 दर्शक:",
        "owner": "मालिक",
        "accountant": "अकाउंटेंट",
        "side_by_side": "दोनों साथ-साथ",
        "owner_version_short": "मालिक",
        "accountant_version_short": "अकाउंटेंट",
        "owner_version": "👤 मालिक संस्करण",
        "accountant_version": "📊 अकाउंटेंट संस्करण",
        "version_missing": "⚠️ इस वर्ष के लिए संस्करण नहीं बना है।",
        "download_short": "⬇ MD",
        "brand_bar_annual": "साल अंत की जीत मासिक अनुशासन से शुरू होती है",
        "page_anomaly_title": "एनोमली रिपोर्ट",
        "page_anomaly_sub": "AI वही पकड़ता है जो इंसान छोड़ देता है · एक्शन सुझाव के साथ",
        "anomaly_folder_missing": "📁 एनोमली फोल्डर अभी तक नहीं मिला।",
        "run_sentinel": "रिपोर्ट बनाने के लिए चलाएँ: `python sentinel.py --all`",
        "no_anomaly_found": "कोई एनोमली रिपोर्ट नहीं मिली।",
        "severity_summary": "गंभीरता का सारांश",
        "critical": "🚨 गंभीर",
        "needs_review": "⚠️ समीक्षा ज़रूरी",
        "minor": "🟡 मामूली",
        "mostly_clean": "⚪ ज़्यादातर ठीक",
        "clean": "✅ ठीक",
        "all_reports": "सभी रिपोर्ट",
        "filter_severity": "🔍 गंभीरता से फिल्टर:",
        "no_match_filter": "ℹ️ चुने हुए फिल्टर से कोई रिपोर्ट मेल नहीं खाती।",
        "brand_bar_anomaly": "जल्दी पकड़ो · तुरंत ठीक करो · आगे रहो",
        "page_qa_title": "अपने P&L से पूछें",
        "page_qa_sub": "AI-संचालित Q&A · असली ABC डेटा पर आधारित · सोर्स के साथ जवाब",
        "chat_controls": "💬 चैट कंट्रोल",
        "back_to_start": "🔄 शुरुआत में लौटें",
        "clear_chat": "🗑 चैट साफ करें",
        "save_session": "💾 मार्कडाउन सेव",
        "export_pdf": "📄 PDF एक्सपोर्ट",
        "session_saved": "✅ सेव हुआ →",
        "nothing_to_save": "अभी सेव करने के लिए कुछ नहीं।",
        "tokens_used": "टोकन यूज़",
        "input_tokens": "📥 इनपुट",
        "output_tokens": "📤 आउटपुट",
        "cache_hits": "⚡ कैश हिट्स",
        "kb_loaded": "📊 ज्ञान आधार लोडेड:",
        "months_briefs_meta": "{months} महीने · {briefs} ब्रीफ/रिपोर्ट · ~{tokens} टोकन कैश्ड",
        "pick_question": "## 💡 सवाल चुनें",
        "dig_deeper": "## 💡 और गहराई से पूछें",
        "chat_placeholder": "💪 या अपना सवाल लिखें...",
        "asking_claude": "💪 डेटा से जवाब निकाल रहा हूँ...",
        "err_no_key": "❌ ANTHROPIC_API_KEY ग़लत या मौजूद नहीं। `.env` फ़ाइल देखें।",
        "err_rate_limit": "❌ रेट लिमिट:",
        "err_api": "❌ API एरर",
        "err_parse": "❌ LLM का जवाब पार्स नहीं हो सका:",
        "brand_bar_qa": "ज्ञान शक्ति है · कुछ भी पूछें · सब जीतें",
    },
}


def t(key: str, **kwargs) -> str:
    """Translate a UI key to current language. Falls back to English if missing."""
    lang = st.session_state.get("lang", "en")
    text = T.get(lang, T["en"]).get(key) or T["en"].get(key, key)
    if kwargs:
        try:
            return text.format(**kwargs)
        except (KeyError, IndexError):
            return text
    return text


def get_lang() -> str:
    return st.session_state.get("lang", "en")


# ─── Indian-number formatting helpers ──────────────────────
def fmt_short_inr(v: float) -> str:
    """₹13.30L / ₹1.45cr / ₹85K / ₹342 — compact Indian style."""
    a = abs(v)
    sign = "-" if v < 0 else ""
    if a >= 1e7:
        return f"{sign}₹{a/1e7:.2f}cr"
    if a >= 1e5:
        return f"{sign}₹{a/1e5:.2f}L"
    if a >= 1e3:
        return f"{sign}₹{a/1e3:.1f}K"
    return f"{sign}₹{a:,.0f}"


def fmt_inr(v: float) -> str:
    """Standard Indian comma format ₹13,30,000."""
    a = abs(v)
    sign = "-" if v < 0 else ""
    s = f"{int(round(a)):,}"
    # Convert Western to Indian comma style (last 3, then every 2)
    if len(s.replace(",", "")) > 3:
        x = s.replace(",", "")
        last3 = x[-3:]
        rest = x[:-3]
        # Group rest in pairs from the right
        chunks = []
        while len(rest) > 2:
            chunks.append(rest[-2:])
            rest = rest[:-2]
        if rest:
            chunks.append(rest)
        s = ",".join(reversed(chunks)) + "," + last3
    return f"{sign}₹{s}"


def fmt_pct(v: float, digits: int = 1) -> str:
    return f"{v:.{digits}f}%"


def fmt_chart_label(v: float, show_currency: bool = True) -> str:
    """Compact label for data-label overlays on charts. '1.2L', '85K', '2.3cr'."""
    a = abs(v)
    sign = "-" if v < 0 else ""
    prefix = "₹" if show_currency else ""
    if a >= 1e7:
        return f"{sign}{prefix}{a/1e7:.2f}cr"
    if a >= 1e5:
        return f"{sign}{prefix}{a/1e5:.2f}L"
    if a >= 1e3:
        return f"{sign}{prefix}{a/1e3:.1f}K"
    return f"{sign}{prefix}{a:.0f}"


def inject_theme():
    """Inject soft light analytics CSS."""
    css = f"""
    <style>
    /* === Soft light theme === */
    .stApp {{
        background: {BG_DEEP};
        color: {TEXT_HI};
    }}

    .main .block-container {{
        padding-top: 1.6rem;
        padding-bottom: 2rem;
        max-width: 1400px;
    }}

    /* Typography */
    h1 {{
        color: {TEXT_HI} !important;
        font-weight: 800 !important;
        letter-spacing: -0.025em;
        font-size: 2.4rem !important;
        margin-bottom: 0.2rem !important;
    }}

    h2 {{
        color: {TEXT_HI} !important;
        font-weight: 700 !important;
        letter-spacing: -0.015em;
        font-size: 1.45rem !important;
        margin-top: 1.5rem !important;
        padding-bottom: 0.5rem !important;
        border-bottom: 1px solid {BORDER};
    }}

    h3 {{
        color: {TEXT_HI} !important;
        font-weight: 700 !important;
        font-size: 1.1rem !important;
    }}

    p, li, label, span {{
        color: {TEXT_MID};
    }}

    /* Sidebar — white panel with subtle shadow */
    [data-testid="stSidebar"] {{
        background: {BG_PANEL} !important;
        border-right: 1px solid {BORDER};
    }}

    [data-testid="stSidebar"] h1,
    [data-testid="stSidebar"] h2,
    [data-testid="stSidebar"] h3,
    [data-testid="stSidebar"] p,
    [data-testid="stSidebar"] label {{
        color: {TEXT_HI} !important;
    }}

    /* Metric */
    [data-testid="stMetric"] {{
        background: {BG_PANEL};
        padding: 1.2rem 1.2rem;
        border-radius: 10px;
        border: 1px solid {BORDER};
        box-shadow: 0 1px 3px rgba(15, 23, 42, 0.04);
        transition: border-color 0.18s, transform 0.18s, box-shadow 0.18s;
    }}

    [data-testid="stMetric"]:hover {{
        border-color: {ACCENT};
        transform: translateY(-2px);
        box-shadow: 0 6px 20px rgba(14, 165, 233, 0.12);
    }}

    [data-testid="stMetricValue"] {{
        color: {TEXT_HI} !important;
        font-size: 2.0rem !important;
        font-weight: 800 !important;
        letter-spacing: -0.025em;
    }}

    [data-testid="stMetricLabel"] {{
        color: {TEXT_MUTED} !important;
        font-weight: 600 !important;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        font-size: 0.74rem !important;
    }}

    [data-testid="stMetricDelta"] {{
        font-weight: 600;
    }}

    /* Buttons */
    .stButton button {{
        background: {ACCENT} !important;
        color: {WHITE} !important;
        border: 1px solid {ACCENT} !important;
        font-weight: 600 !important;
        letter-spacing: 0.01em;
        border-radius: 6px;
        transition: all 0.15s;
        padding: 0.4rem 1rem;
        box-shadow: 0 1px 2px rgba(15, 23, 42, 0.06);
    }}

    .stButton button:hover {{
        background: {ACCENT_HI} !important;
        border-color: {ACCENT_HI} !important;
        color: {WHITE} !important;
        transform: translateY(-1px);
        box-shadow: 0 4px 10px rgba(14, 165, 233, 0.2);
    }}

    .stButton button[kind="secondary"] {{
        background: {BG_PANEL} !important;
        color: {TEXT_HI} !important;
        border: 1px solid {BORDER_HI} !important;
    }}

    .stButton button[kind="secondary"]:hover {{
        background: {BG_PANEL_HI} !important;
        border-color: {ACCENT} !important;
        color: {ACCENT_HI} !important;
    }}

    /* Download button — outlined */
    .stDownloadButton button {{
        background: {BG_PANEL} !important;
        border: 1px solid {ACCENT} !important;
        color: {ACCENT_HI} !important;
        font-weight: 600;
    }}

    .stDownloadButton button:hover {{
        background: {ACCENT_SOFT_BG} !important;
        color: {ACCENT_DEEP} !important;
    }}

    /* Alerts */
    .stAlert {{
        background: {BG_PANEL} !important;
        border: 1px solid {BORDER} !important;
        border-left: 3px solid {ACCENT} !important;
        color: {TEXT_HI} !important;
        border-radius: 8px;
    }}

    /* Inputs */
    .stTextInput input,
    .stSelectbox div[data-baseweb="select"] > div,
    .stChatInput textarea,
    .stChatInput input {{
        background-color: {BG_PANEL} !important;
        color: {TEXT_HI} !important;
        border: 1px solid {BORDER_HI} !important;
    }}

    .stTextInput input:focus,
    .stChatInput textarea:focus,
    .stChatInput input:focus {{
        border-color: {ACCENT} !important;
        box-shadow: 0 0 0 3px rgba(14, 165, 233, 0.18) !important;
    }}

    /* Chat messages */
    [data-testid="stChatMessage"] {{
        background-color: {BG_PANEL} !important;
        border-radius: 10px;
        border: 1px solid {BORDER};
        box-shadow: 0 1px 2px rgba(15, 23, 42, 0.04);
    }}

    /* Expander */
    .streamlit-expanderHeader, [data-testid="stExpander"] summary {{
        background-color: {BG_PANEL} !important;
        color: {TEXT_HI} !important;
        font-weight: 600;
        border: 1px solid {BORDER} !important;
        border-radius: 8px !important;
    }}

    /* Divider */
    hr {{
        border-color: {BORDER} !important;
        opacity: 1;
    }}

    /* Logo wrap */
    .brand-logo-wrap {{
        text-align: center;
        padding: 0.4rem;
    }}

    /* Quote banner */
    .brand-quote-banner {{
        background: {ACCENT_SOFT_BG};
        border-left: 3px solid {ACCENT};
        padding: 0.85rem 1.4rem;
        border-radius: 6px;
        text-align: left;
        color: {ACCENT_DEEP};
        font-size: 1.02rem;
        font-weight: 500;
        font-style: italic;
        margin: 0.8rem 0 1.3rem 0;
    }}

    /* Brand bar */
    .brand-bar {{
        background: {BG_PANEL};
        border: 1px solid {BORDER};
        padding: 0.5rem 1rem;
        border-radius: 6px;
        text-align: center;
        color: {TEXT_MUTED};
        font-weight: 600;
        letter-spacing: 0.12em;
        font-size: 0.75rem;
        text-transform: uppercase;
    }}

    /* Footer / menu hide */
    footer {{visibility: hidden;}}
    #MainMenu {{visibility: hidden;}}

    /* KPI tile — dual format */
    .brand-kpi {{
        background: {BG_PANEL};
        border: 1px solid {BORDER};
        border-top: 3px solid {ACCENT};
        padding: 1.1rem 1.2rem 1.0rem 1.2rem;
        border-radius: 10px;
        text-align: left;
        box-shadow: 0 1px 3px rgba(15, 23, 42, 0.04);
        transition: transform 0.18s, border-color 0.18s, box-shadow 0.18s;
        height: 100%;
    }}

    .brand-kpi:hover {{
        transform: translateY(-2px);
        border-top-color: {ACCENT_HI};
        box-shadow: 0 6px 18px rgba(14, 165, 233, 0.12);
    }}

    .brand-kpi-label {{
        color: {TEXT_MUTED};
        text-transform: uppercase;
        font-size: 0.7rem;
        letter-spacing: 0.1em;
        font-weight: 600;
        margin-bottom: 0.5rem;
    }}

    .brand-kpi-value {{
        font-size: 2.0rem;
        color: {TEXT_HI};
        font-weight: 800;
        letter-spacing: -0.03em;
        line-height: 1.05;
    }}

    .brand-kpi-actual {{
        color: {TEXT_MUTED};
        font-size: 0.78rem;
        margin-top: 0.18rem;
        font-weight: 500;
        font-variant-numeric: tabular-nums;
    }}

    .brand-kpi-sub {{
        color: {TEXT_MID};
        font-size: 0.8rem;
        margin-top: 0.25rem;
        font-weight: 500;
    }}

    .brand-kpi-delta-up {{
        color: {SUCCESS};
        font-size: 0.78rem;
        font-weight: 600;
        margin-top: 0.2rem;
    }}

    .brand-kpi-delta-down {{
        color: {DANGER};
        font-size: 0.78rem;
        font-weight: 600;
        margin-top: 0.2rem;
    }}

    /* Sidebar caption tweaks */
    [data-testid="stSidebar"] .stCaption {{
        color: {TEXT_MUTED} !important;
    }}

    /* Tables — clean light look */
    [data-testid="stDataFrame"] {{
        background: {BG_PANEL};
        border-radius: 8px;
        border: 1px solid {BORDER};
    }}

    /* ── Mobile (<768px) ─────────────────────────────────── */
    @media (max-width: 768px) {{
        .main .block-container {{
            padding-top: 0.8rem !important;
            padding-left: 0.8rem !important;
            padding-right: 0.8rem !important;
        }}
        h1 {{ font-size: 1.7rem !important; }}
        h2 {{ font-size: 1.15rem !important; margin-top: 1.1rem !important; }}
        h3 {{ font-size: 1.0rem !important; }}
        [data-testid="stMetricValue"] {{ font-size: 1.5rem !important; }}
        [data-testid="stMetricLabel"] {{ font-size: 0.7rem !important; }}
        .brand-kpi {{ padding: 0.95rem 0.85rem 0.85rem 0.85rem; }}
        .brand-kpi-value {{ font-size: 1.5rem; }}
        .brand-kpi-label {{ font-size: 0.65rem; }}
        .brand-kpi-actual {{ font-size: 0.72rem; }}
        .brand-quote-banner {{ font-size: 0.9rem; padding: 0.7rem 1rem; }}
        .brand-bar {{ font-size: 0.62rem; letter-spacing: 0.08em; padding: 0.4rem 0.6rem; }}
        .stButton button {{ font-size: 0.85rem; padding: 0.35rem 0.7rem; }}
        [data-testid="stChatMessage"] {{ padding: 0.6rem !important; }}
    }}
    </style>
    """
    st.markdown(css, unsafe_allow_html=True)


def _img_to_base64(path: Path) -> str:
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode()


def show_logo(width: int = 140) -> None:
    target = LOGO_PATH if LOGO_PATH.exists() else (LOGO_FALLBACK if LOGO_FALLBACK.exists() else None)
    if target:
        data = _img_to_base64(target)
        st.markdown(
            f'<div class="brand-logo-wrap"><img src="data:image/png;base64,{data}" '
            f'width="{width}" style="border-radius: 50%;"/></div>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            f'<div class="brand-logo-wrap" style="font-size:1.8rem; font-weight:900; color:{TEXT_HI};">ABC</div>',
            unsafe_allow_html=True,
        )


def quote_banner() -> None:
    lang = st.session_state.get("lang", "en")
    quote = random.choice(QUOTES.get(lang, QUOTES["en"]))
    st.markdown(f'<div class="brand-quote-banner">💪 "{quote}"</div>', unsafe_allow_html=True)


def brand_bar(text: str = "ABC FITNESS CLUB · SINCE 2020") -> None:
    st.markdown(f'<div class="brand-bar">{text}</div>', unsafe_allow_html=True)


def language_toggle_sidebar() -> None:
    if "lang" not in st.session_state:
        st.session_state.lang = "en"
    st.markdown(
        f'<div style="color:{TEXT_MUTED}; font-size:0.7rem; font-weight:700; '
        f'text-transform:uppercase; letter-spacing:0.12em; text-align:center; margin-bottom:0.4rem;">'
        f'🌐 {t("language")}</div>',
        unsafe_allow_html=True,
    )
    c1, c2 = st.columns(2)
    with c1:
        if st.button(
            "EN", use_container_width=True,
            type="primary" if st.session_state.lang == "en" else "secondary",
            key="lang_btn_en",
        ):
            st.session_state.lang = "en"
            st.rerun()
    with c2:
        if st.button(
            "हिं", use_container_width=True,
            type="primary" if st.session_state.lang == "hi" else "secondary",
            key="lang_btn_hi",
        ):
            st.session_state.lang = "hi"
            st.rerun()


def data_source_picker() -> None:
    """Static label — this workspace is LOCKED to a single source (no dropdown)."""
    from data_sources import active_source  # noqa: PLC0415

    src = active_source()
    exists = src.master_path.exists()
    status_color = SUCCESS if exists else DANGER
    status_text = "✓ master found" if exists else "⚠ master missing"

    st.markdown(
        f'<div style="color:{TEXT_MUTED}; font-size:0.7rem; font-weight:700; '
        f'text-transform:uppercase; letter-spacing:0.12em; margin-bottom:0.3rem;">'
        f'📂 DATA SOURCE</div>'
        f'<div style="background:{BG_PANEL_HI}; border:1px solid {BORDER}; '
        f'border-radius:6px; padding:0.5rem 0.7rem;">'
        f'<div style="color:{TEXT_HI}; font-weight:700; font-size:0.85rem;">{src.label}</div>'
        f'<div style="font-size:0.7rem; color:{TEXT_MUTED}; margin-top:0.2rem;">'
        f'<span style="color:{status_color}; font-weight:700;">{status_text}</span> · '
        f'<code style="font-size:0.68rem; color:{TEXT_MID};">{src.master_path.name}</code>'
        f'</div></div>',
        unsafe_allow_html=True,
    )


def sidebar_branding() -> None:
    with st.sidebar:
        show_logo(width=140)
        st.markdown(
            '<div style="text-align:center; padding: 0.6rem 0 0.4rem 0;">'
            f'<div style="color:{TEXT_HI}; font-size:0.85rem; letter-spacing:0.08em; '
            f'text-transform:uppercase; font-weight:700;">{t("since")}</div>'
            f'<div style="display:inline-block; margin-top:0.55rem; padding:0.22rem 0.7rem; '
            f'background:{ACCENT_SOFT_BG}; color:{ACCENT_DEEP}; font-size:0.65rem; font-weight:700; '
            f'letter-spacing:0.12em; text-transform:uppercase; border-radius:4px; '
            f'border:1px solid {ACCENT};">'
            f'{t("powered_by")}</div>'
            '</div>',
            unsafe_allow_html=True,
        )
        st.markdown("---")
        data_source_picker()
        st.markdown("---")
        language_toggle_sidebar()
        st.markdown("---")


def kpi_tile(value: str, label: str, sub: str = "", actual: str = "",
             delta: str = "", delta_positive: bool = True,
             accent_color: str | None = None) -> None:
    """Premium KPI tile with short value + (optional) exact actual + (optional) delta + (optional) sub.

    value:   short label e.g. '₹13.30L'
    actual:  full-precision e.g. '₹13,30,000'  (rendered smaller, muted)
    delta:   '+18.2% vs prev' rendered green/red below actual
    sub:     extra context line (e.g. '12 mo · all segments')
    """
    border_color = accent_color or ACCENT
    html = (
        f'<div class="brand-kpi" style="border-top-color:{border_color};">'
        f'<div class="brand-kpi-label">{label}</div>'
        f'<div class="brand-kpi-value">{value}</div>'
    )
    if actual:
        html += f'<div class="brand-kpi-actual">{actual}</div>'
    if delta:
        cls = "brand-kpi-delta-up" if delta_positive else "brand-kpi-delta-down"
        html += f'<div class="{cls}">{delta}</div>'
    if sub:
        html += f'<div class="brand-kpi-sub">{sub}</div>'
    html += '</div>'
    st.markdown(html, unsafe_allow_html=True)
